'use client';
import { useState,type FormEvent } from 'react';
import { ArrowUpRight,Check,LoaderCircle } from 'lucide-react';
export default function BookingForm({eventType,setEventType,today}:{eventType:string;setEventType:(s:string)=>void;today:string}){
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [receipt,setReceipt]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');const data=Object.fromEntries(new FormData(e.currentTarget));try{const response=await fetch('/api/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,consent:data.consent==='on'})});const result=await response.json() as {id:string;error?:string};if(!response.ok)throw new Error(result.error||'Please try again.');setReceipt(result.id);}catch(err){setError(err instanceof Error?err.message:'Something went wrong. Please try again.');}finally{setBusy(false);}}
 if(receipt)return <div className="booking-card success-card" role="status"><span className="success-icon"><Check size={34}/></span><p className="eyebrow">SAFELY IN SANTA’S INBOX</p><h3>Your request is in!</h3><p>Your details have been saved for review. Your visit is not confirmed yet; availability and pricing need to be agreed with Fred.</p><p className="receipt">Reference: {receipt.slice(0,8).toUpperCase()}</p><p className="quiet-note">Preview note: no email notification is sent.</p><button className="button primary" onClick={()=>setReceipt('')}>Send another request</button></div>;
 return <form className="booking-card" onSubmit={submit}><div className="form-title"><h3>A visit to remember</h3><span>STARTS HERE</span></div><p className="form-subtitle">All fields are required except your message.</p><div className="form-grid"><label>Your name<input name="name" autoComplete="name" placeholder="First and last name" required minLength={2} maxLength={100}/></label><label>Email address<input name="email" type="email" autoComplete="email" placeholder="you@example.com" required maxLength={200}/></label><label>Phone number<input name="phone" type="tel" autoComplete="tel" placeholder="Your contact number" required minLength={7} maxLength={40}/></label><label>What are we celebrating?<select name="eventType" value={eventType} onChange={e=>setEventType(e.target.value)}><option>Home visit</option><option>Holiday party</option><option>Community event</option><option>Photo session</option></select></label><label>Preferred date<input name="date" type="date" min={today} required/></label><label>Preferred time <span className="label-note">(Pacific)</span><input name="time" type="time" required/></label><label className="full-width">Visit length<select name="duration" defaultValue="1 hour"><option>30 minutes</option><option>1 hour</option><option>90 minutes</option><option>2 hours</option><option>Let’s discuss</option></select></label><label className="full-width">Event location<input name="location" placeholder="Venue or address, and city" autoComplete="street-address" required minLength={3} maxLength={300}/></label><label className="full-width">A little about your gathering <span className="label-note">(optional)</span><textarea name="notes" placeholder="Guest numbers, special requests, and the magic you have in mind…" rows={3} maxLength={2000}/></label></div><label className="honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><label className="checkbox-label"><input name="consent" type="checkbox" required/><span>I agree to be contacted about this request and have read the <a href="/privacy">privacy notice</a>.</span></label>{error?<p className="form-error" role="alert">{error}</p>:null}<button className="button primary submit-button" disabled={busy}>{busy?<><LoaderCircle size={18} className="spin"/>Saving your request…</>:<>Send my Christmas wish <ArrowUpRight size={19}/></>}</button><p className="form-disclaimer">A request, not a reservation. Fred will confirm the details personally.</p></form>;
}
