'use client';
import { useRef,useState } from 'react';
import { ArrowUpRight,ArrowRight,Gift,MapPin,CalendarDays,Clock,ChevronLeft,ChevronRight,Menu,X,Sparkles,Heart,Camera,Check,TreePine } from 'lucide-react';
import { type SiteContent,type Photo,monday,shiftDay,clock } from '@/lib/content';
import BookingForm from './BookingForm';
const services=[{icon:Gift,title:'A visit to your home',copy:'A knock at the door. A familiar “ho ho ho.” A little wonder for the whole family.',type:'Home visit'},{icon:Sparkles,title:'A party to remember',copy:'Bring a festive guest of honour to your workplace celebration or holiday gathering.',type:'Holiday party'},{icon:Camera,title:'Moments worth keeping',copy:'Make space for smiles, a Christmas wish, and a photo you’ll come back to every year.',type:'Photo session'}];
export default function Home({site,today}:{site:SiteContent;today:string}){
 const [menu,setMenu]=useState(false);const [eventType,setEventType]=useState('Home visit');
 const upcoming=site.appearances.filter(a=>a.date>=today).sort((a,b)=>a.date.localeCompare(b.date));
 const [week,setWeek]=useState(monday(upcoming[0]?.date||today));
 const [category,setCategory]=useState('All moments');const [photo,setPhoto]=useState<Photo|null>(null);const dialog=useRef<HTMLDialogElement>(null);
 const photos=site.photos.filter(p=>category==='All moments'||p.category===category);
 const categories=['All moments',...new Set(site.photos.map(p=>p.category))];
 const weekEvents=site.appearances.filter(a=>a.date>=week&&a.date<=shiftDay(week,6));
 const formatDate=(d:string,options:Intl.DateTimeFormatOptions)=>new Date(`${d}T12:00:00Z`).toLocaleDateString('en-US',{...options,timeZone:'UTC'});
 function chooseVisit(type:string){setEventType(type);document.getElementById('book')?.scrollIntoView({behavior:'smooth'});}
 return <>
 <a href="#main" className="skip-link">Skip to content</a>
 <div className="announcement"><span>✧</span> A little wonder. A lot of Christmas spirit. <span>✧</span></div>
 <header className="site-header"><a className="brand" href="#"><span className="brand-mark"><TreePine size={27}/></span><span>Fred <i>the</i> Santa<small>CHRISTMAS, IN PERSON.</small></span></a><nav aria-label="Main navigation" className={menu?'open':''}><a href="#about" onClick={()=>setMenu(false)}>Meet Fred</a><a href="#visits" onClick={()=>setMenu(false)}>Santa visits</a><a href="#schedule" onClick={()=>setMenu(false)}>Find Santa</a><a href="#gallery" onClick={()=>setMenu(false)}>The gallery</a></nav><a className="button primary nav-book" href="#book">Book a visit <ArrowUpRight size={17}/></a><button className="icon-button menu-toggle" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 <main id="main">
 <section className="hero section-shell"><div className="hero-copy"><p className="eyebrow"><span className="tiny-star">✳</span> THE MOST WONDERFUL GUEST OF THE YEAR</p><h1>A little Christmas<br/>magic.<br/><em>At your doorstep.</em></h1><p className="hero-description">The wide eyes. The warm smiles. The memories that stay.<br className="desktop-break"/> Make your Christmas a little more magical with Santa Fred.</p><div className="hero-actions"><a className="button primary" href="#book">Invite Santa over <ArrowUpRight size={18}/></a><a className="text-link" href="#schedule">Where’s Santa? <ArrowRight size={17}/></a></div><div className="hero-note"><Gift size={20}/><span>For little believers & the young at heart.</span></div></div><div className="hero-visual"><div className="photo-frame"><img src={site.heroImage} alt="Sample Santa portrait, to be replaced with Fred’s photo" fetchPriority="high" width="1536" height="1024"/><span className="photo-label">A LITTLE PREVIEW OF THE MAGIC</span></div><div className="seal"><span>FROM THE</span><Sparkles size={28}/><strong>North Pole</strong><span>WITH LOVE</span></div><div className="photo-caption"><span className="handwritten">Oh, what a joy!</span><span>FRED BERG · YOUR SANTA</span></div></div></section>
 <div className="ribbon"><span>Home visits</span><b>✧</b><span>Holiday parties</span><b>✧</b><span>Community celebrations</span><b>✧</b><span>Christmas memories</span><b>✧</b></div>
 <section id="visits" className="section-shell visits"><div className="section-heading"><div><p className="eyebrow">MAKE THE SEASON YOURS</p><h2>Every gathering deserves<br/>a little <em>wonder.</em></h2></div><p>From a cosy living room to a room full of cheer,<br/>there’s a Santa visit for your kind of Christmas.</p></div><div className="service-grid">{services.map((s,i)=><article className="service" key={s.title}><span className="service-number">0{i+1}</span><s.icon size={30} strokeWidth={1.25}/><h3>{s.title}</h3><p>{s.copy}</p><button className="text-link" onClick={()=>chooseVisit(s.type)}>Plan this visit <ArrowUpRight size={17}/></button></article>)}</div><p className="quiet-note">Every visit begins with a conversation. Timing, details, and pricing are confirmed personally.</p></section>
 <section id="about" className="about section-shell"><div className="about-image"><img src={site.heroImage} alt="Sample Santa sitting beside a Christmas tree" width="600" height="600" loading="lazy"/><span>GOOD TIDINGS START WITH A HELLO.</span></div><div className="about-copy"><p className="eyebrow">THE MAN BEHIND THE MERRY</p><h2>Meet Fred.<br/><em>Your Santa.</em></h2><p>Christmas has a way of bringing us together. A shared story, a little laughter, a moment of wonder — sometimes the smallest things become the memories we keep.</p><p>Fred Berg is getting ready to bring that Christmas spirit to your gatherings. Whether you’re planning a family surprise or a festive celebration, let’s make room for something special.</p><a className="text-link" href="#book">Let’s plan a little magic <ArrowUpRight size={17}/></a><div className="signature">With Christmas cheer, <strong>Fred</strong></div></div></section>
 <section id="schedule" className="schedule-section"><div className="section-shell"><div className="section-heading"><div><p className="eyebrow">FOLLOW THE FESTIVE FOOTSTEPS</p><h2>Where’s Santa <em>this week?</em></h2></div><p>Find a public appearance and stop by to say hello.<br/>Private visits stay between Santa and his guests.</p></div><div className="calendar"><div className="calendar-toolbar"><div><CalendarDays size={20}/><strong>{formatDate(week,{month:'long',day:'numeric'})} – {formatDate(shiftDay(week,6),{month:'long',day:'numeric',year:'numeric'})}</strong></div><div><button className="week-today" onClick={()=>setWeek(monday(today))}>This week</button><button className="icon-button" aria-label="Previous week" onClick={()=>setWeek(shiftDay(week,-7))}><ChevronLeft size={19}/></button><button className="icon-button" aria-label="Next week" onClick={()=>setWeek(shiftDay(week,7))}><ChevronRight size={19}/></button></div></div><div className="calendar-grid">{Array.from({length:7},(_,i)=>{const date=shiftDay(week,i);const events=weekEvents.filter(a=>a.date===date).sort((a,b)=>a.start.localeCompare(b.start));return <div className={`calendar-day ${date===today?'is-today':''}`} key={date}><div className="day-heading"><span>{formatDate(date,{weekday:'short'})}</span><strong>{formatDate(date,{day:'numeric'})}</strong></div>{events.length?events.map(a=><article className="appearance" key={a.id}>{a.sample?<span className="sample-tag">SAMPLE</span>:null}<p className="event-time">{clock(a.start)} – {clock(a.end)}</p><h3>{a.title}</h3><p><MapPin size={13}/>{a.venue}</p>{a.sample?<small>Details to be confirmed</small>:a.address?<a target="_blank" rel="noopener noreferrer" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(a.address)}`}>Directions <ArrowUpRight size={12}/></a>:null}</article>):<p className="no-event">No public<br/>appearance</p>}</div>;})}</div></div><div className="schedule-footer"><span><span className="legend-dot"/> Public appearances · Pacific time</span><span>{weekEvents.some(a=>a.sample)?'Sample schedule — these are not confirmed appearances.':'Appearances are updated as plans are confirmed.'}</span></div><div className="schedule-invite"><Gift size={20}/><p>Want Santa all to yourselves?</p><a href="#book">Request a private visit <ArrowRight size={16}/></a></div></div></section>
 <section id="gallery" className="section-shell gallery"><div className="section-heading"><div><p className="eyebrow">A SEASON OF LITTLE MOMENTS</p><h2>Christmas looks good <em>on you.</em></h2></div><p>A glimpse of the magic.<br/>Real memories and Fred’s photos are coming soon.</p></div><div className="gallery-filters" role="group" aria-label="Filter gallery">{categories.map(c=><button key={c} className={category===c?'selected':''} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="gallery-grid">{photos.map((p,i)=><button className={`gallery-item gallery-item-${i%4}`} key={p.id} onClick={()=>{setPhoto(p);dialog.current?.showModal();}} aria-label={`Enlarge: ${p.caption}`}><img src={p.src} alt={p.caption} width="600" height="650" loading="lazy"/><span><span>{p.caption}</span><ArrowUpRight size={21}/></span></button>)}</div>{!photos.length?<p className="empty-state">The next chapter of Christmas memories is on its way.</p>:null}<p className="quiet-note">One sample Santa image is used throughout this preview. Replace it with Fred’s own photos when ready.</p></section>
 <section className="booking-section" id="book"><div className="section-shell booking-layout"><div className="booking-intro"><p className="eyebrow">LET’S PUT SOMETHING MAGICAL IN THE DIARY</p><h2>Dear Santa,<br/><em>you’re invited.</em></h2><p>Tell us a little about your gathering. Fred can review the details and get in touch to plan your visit.</p><ol className="booking-steps"><li><span>01</span><div><strong>Share your Christmas plans</strong><p>A date, a place, and a little about your event.</p></div></li><li><span>02</span><div><strong>Work out the merry details</strong><p>Fred reviews timing, travel, and your requests.</p></div></li><li><span>03</span><div><strong>Let the countdown begin</strong><p>Your visit is booked once personally confirmed.</p></div></li></ol><div className="booking-footnote"><Heart size={19}/><span>No payment is collected with your request.</span></div></div><BookingForm eventType={eventType} setEventType={setEventType} today={today}/></div></section>
 <section className="section-shell faq"><div><p className="eyebrow">A FEW THINGS YOU MIGHT BE WONDERING</p><h2>Santa’s little <em>FAQ.</em></h2></div><div>{[{q:'How do I book a visit?',a:'Send a request with your preferred date, time, and location. Fred reviews each request before confirming availability, pricing, and the visit details. Submitting a request does not reserve a time.'},{q:'Where does Santa travel?',a:'Include your event location in the form. Fred will confirm whether he can travel to you and discuss any travel arrangements. The service area is still being finalised.'},{q:'Can we take photos?',a:'Let Fred know you would like time for photos when you request your visit, so it can be included in the plan.'},{q:'Are the appearances on the calendar confirmed?',a:'Entries marked “Sample” show how the timetable will look. They are not real scheduled events. Confirmed public appearances will replace them as Fred’s plans are finalised.'}].map(item=><details key={item.q}><summary>{item.q}<span>+</span></summary><p>{item.a}</p></details>)}</div></section>
 </main><footer className="footer"><div className="section-shell"><div className="footer-top"><a className="brand" href="#"><TreePine size={29}/><span>Fred <i>the</i> Santa<small>A LITTLE CHRISTMAS MAGIC.</small></span></a><p>For the moments that become traditions.</p><a href="#book" className="text-link">Make a little magic <ArrowUpRight size={17}/></a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Fred Berg. With Christmas cheer.</span><div><a href="/privacy">Privacy</a><a href="/manage">Santa’s workshop <ArrowUpRight size={13}/></a></div></div></div></footer>
 <dialog ref={dialog} className="lightbox" onClick={e=>{if(e.target===e.currentTarget)dialog.current?.close();}}><button className="lightbox-close icon-button" aria-label="Close photo" onClick={()=>dialog.current?.close()}><X/></button>{photo?<><img src={photo.src} alt={photo.caption}/><p>{photo.caption}</p></>:null}</dialog>
 </>;
}
