'use client';
import { useEffect,useState,type ChangeEvent } from 'react';
import { ArrowUpRight,Plus,RefreshCw } from 'lucide-react';
import { type SiteContent,PLACEHOLDER,clock } from '@/lib/content';
type Booking={id:string;name:string;email:string;phone:string;date:string;time:string;duration:string;eventType:string;location:string;notes:string;status:string;createdAt:string};
export default function Workshop(){
 const [tab,setTab]=useState('Requests');const [requests,setRequests]=useState<Booking[]>([]);const [site,setSite]=useState<SiteContent|null>(null);const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [message,setMessage]=useState('');const [error,setError]=useState('');const [dirty,setDirty]=useState(false);
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/admin');const d=await r.json() as {requests:Booking[];site:SiteContent;error?:string};if(!r.ok)throw new Error(d.error);setRequests(d.requests);setSite(d.site);setDirty(false);}catch(e){setError(e instanceof Error?e.message:'Could not load the workshop.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 async function mutate(body:unknown,success:string){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/admin',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);setMessage(success);return true;}catch(e){setError(e instanceof Error?e.message:'Could not save. Try again.');return false;}finally{setBusy(false);}}
 function update(next:SiteContent){setSite(next);setDirty(true);setMessage('');}
 async function save(){if(site&&await mutate({site},'Changes saved. They are now visible on the website.'))setDirty(false);}
 async function status(id:string,status:string){if(await mutate({action:'status',id,status},'Status updated. No email has been sent; contact the guest directly.'))setRequests(v=>v.map(r=>r.id===id?{...r,status}:r));}
 async function remove(id:string){if(!confirm('Permanently delete this booking request?'))return;if(await mutate({action:'deleteRequest',id},'Request deleted.'))setRequests(v=>v.filter(r=>r.id!==id));}
 async function upload(e:ChangeEvent<HTMLInputElement>,index:number|'hero'){
 const file=e.target.files?.[0];if(!file||!site)return;setBusy(true);setError('');setMessage('');const body=new FormData();body.set('photo',file);try{const r=await fetch('/api/photos',{method:'POST',body});const d=await r.json() as {src:string;error?:string};if(!r.ok)throw new Error(d.error);if(index==='hero'){update({...site,heroImage:d.src});}else{update({...site,photos:site.photos.map((p,i)=>i===index?{...p,src:d.src}:p)});}setMessage('Photo uploaded. Save changes to publish it on the website.');}catch(e){setError(e instanceof Error?e.message:'Upload failed.');}finally{setBusy(false);e.target.value='';}}
 function editAppearance(index:number,key:string,value:string|boolean){if(site)update({...site,appearances:site.appearances.map((a,i)=>i===index?{...a,[key]:value}:a)});}
 function editPhoto(index:number,key:string,value:string){if(site)update({...site,photos:site.photos.map((p,i)=>i===index?{...p,[key]:value}:p)});}
 return <main className="manage-shell"><div className="manage-head"><div><p className="eyebrow">FRED THE SANTA · MANAGEMENT</p><h1>Santa’s workshop</h1></div><a href="/" className="button secondary">View website <ArrowUpRight size={16}/></a></div><div className="admin-notice">Private review workspace. Requests are saved here; no email notifications are sent. Confirm pricing, travel, and timing with guests before approving a visit.</div><div className="manage-nav" role="group" aria-label="Workshop section">{['Requests','Appearances','Photos'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>{setTab(t);setMessage('');setError('');}}>{t}{t==='Requests'?` (${requests.filter(r=>r.status==='pending').length})`:''}</button>)}</div>{message?<p className="admin-message" role="status">{message}</p>:null}{error?<p className="admin-message admin-error" role="alert">{error}</p>:null}{loading?<p>Opening the workshop…</p>:null}{!loading&&!site?<button className="button secondary" onClick={load}>Try again</button>:null}
 {site&&!loading&&tab==='Requests'?<><div className="manage-footer" style={{margin:'0 0 20px'}}><p className="quiet-note">Requests are private. Approval does not add an event to the public calendar.</p><button className="icon-button" aria-label="Refresh requests" onClick={()=>{if(!dirty||confirm('Discard unsaved content changes and refresh?'))void load();}}><RefreshCw size={17}/></button></div>{requests.length?requests.map(r=><article className="request-card" key={r.id}><div className="request-head"><div><h3>{r.name}</h3><p>{r.eventType} · {r.id.slice(0,8).toUpperCase()}</p></div><span className={`status status-${r.status}`}>{r.status}</span></div><div className="request-meta"><strong>{r.date} · {clock(r.time)} Pacific</strong><span>{r.duration}</span><span>{r.location}</span></div><p><a href={`mailto:${r.email}`}>{r.email}</a> · <a href={`tel:${r.phone.replace(/[^+\d]/g,'')}`}>{r.phone}</a></p>{r.notes?<p>{r.notes}</p>:null}<div className="admin-actions"><button disabled={busy||r.status==='approved'} onClick={()=>void status(r.id,'approved')}>Mark approved</button><button disabled={busy||r.status==='declined'} onClick={()=>void status(r.id,'declined')}>Decline</button><button disabled={busy||r.status==='pending'} onClick={()=>void status(r.id,'pending')}>Return to pending</button><button className="danger" disabled={busy} onClick={()=>void remove(r.id)}>Delete request</button></div></article>):<div className="empty-state"><h3>The diary is ready.</h3><p>New requests will appear here. Try the booking form on the website to see the full flow.</p></div>}</>:null}
 {site&&!loading&&tab==='Appearances'?<><p className="quiet-note">Only add events where visitors are welcome. All times are Pacific. Entries marked “Sample” will be clearly labelled on the website.</p>{site.appearances.map((a,i)=><article className="editor-card" key={a.id}><div className="form-grid"><label>Event name<input value={a.title} maxLength={100} onChange={e=>editAppearance(i,'title',e.target.value)}/></label><label>Venue<input value={a.venue} maxLength={100} onChange={e=>editAppearance(i,'venue',e.target.value)}/></label><label>Date<input type="date" value={a.date} onChange={e=>editAppearance(i,'date',e.target.value)}/></label><label>Start time<input type="time" value={a.start} onChange={e=>editAppearance(i,'start',e.target.value)}/></label><label>End time<input type="time" value={a.end} onChange={e=>editAppearance(i,'end',e.target.value)}/></label><label>Address for directions<input value={a.address} maxLength={300} onChange={e=>editAppearance(i,'address',e.target.value)}/></label></div><label className="checkbox-label"><input type="checkbox" checked={a.sample} onChange={e=>editAppearance(i,'sample',e.target.checked)}/>Sample entry (not a confirmed event)</label><div className="admin-actions"><button className="danger" onClick={()=>{if(confirm('Remove this appearance from the calendar?'))update({...site,appearances:site.appearances.filter((_,n)=>n!==i)});}}>Remove appearance</button></div></article>)}<button className="button secondary" onClick={()=>update({...site,appearances:[...site.appearances,{id:crypto.randomUUID(),date:'2026-12-01',start:'12:00',end:'14:00',title:'New appearance',venue:'Venue to be confirmed',address:'',sample:true}]})}><Plus size={16}/>Add appearance</button></>:null}
 {site&&!loading&&tab==='Photos'?<><p className="quiet-note">Upload JPG, PNG, or WebP files under 8 MB. Add only photos you have permission to publish.</p><article className="editor-card"><h3>Main portrait</h3><div className="admin-photo-row"><img src={site.heroImage} alt="Current main portrait"/><div><p>Used in the main introduction and Meet Fred section.</p><label>Replace the main portrait<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>void upload(e,'hero')}/></label></div></div></article>{site.photos.map((p,i)=><article className="editor-card" key={p.id}><div className="admin-photo-row"><img src={p.src} alt={p.caption}/><div><label>Caption<input value={p.caption} maxLength={120} onChange={e=>editPhoto(i,'caption',e.target.value)}/></label><label>Category<input value={p.category} maxLength={50} onChange={e=>editPhoto(i,'category',e.target.value)}/></label><label>Replace photo<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>void upload(e,i)}/></label><div className="admin-actions"><button onClick={()=>update({...site,heroImage:p.src})}>Use as main portrait</button><button className="danger" onClick={()=>{if(confirm('Remove this photo from the gallery?'))update({...site,photos:site.photos.filter((_,n)=>n!==i)});}}>Remove from gallery</button></div></div></div></article>)}<button className="button secondary" onClick={()=>update({...site,photos:[...site.photos,{id:crypto.randomUUID(),src:PLACEHOLDER,caption:'A Christmas moment',category:'Christmas magic'}]})}><Plus size={16}/>Add gallery photo</button></>:null}
 {site&&tab!=='Requests'?<div className="manage-footer"><p className="quiet-note">{dirty?'You have unsaved changes.':'All changes saved.'}</p><button disabled={busy||!dirty} className="button primary" onClick={()=>void save()}>{busy?'Saving…':'Save changes'}</button></div>:null}</main>;
}
